apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_URL: "postgres://username:password@postgres-host:5432/acme"
  METRICS_URL: "http://metrics-service.default.svc.cluster.local:80"
